{{- if .Values.service.targetGroupArn -}}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "microservice-chart.fullname" . }}
spec:
  serviceRef:
    name: {{ include "microservice-chart.fullname" . }}
    port: {{ .Values.service.port }}
  targetGroupARN: {{ .Values.service.targetGroupArn }}
{{- end }}
