replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  tag: ""
  port: 80

env: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

livenessProbe:
  httpGet:
    path: /healthz/live
    port: 8080
  initialDelaySeconds: 60
  failureThreshold: 6
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz/ready
    port: 8080
  initialDelaySeconds: 60
  failureThreshold: 6
  periodSeconds: 10

resources:
  requests:
    memory: "96Mi"
    cpu: "40m"
  limits:
    memory: "128Mi"
    cpu: "150m"

nodeSelector: {}

tolerations: []

affinity: {}

targetGroupBinding:
  create: false
  arn: ""

autoscaling:
  enable: false
  minReplica: 1
  maxReplica: 1
  pollingInterval: 10 # seconds
  cooldownPeriod: 300 # seconds
  triggers: []
